name: Generate feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run feed Generator
        uses: me-AC/podcast-generator@main
    
